#pragma once

#include <GL/glew.h>
#include <GLFW/glfw3.h>
#include <GL/glut.h>
#include <iostream>
#include <fstream>
#include <vector>
#include <algorithm>
#include <string>
#include <map>
#include <functional>
#include <cmath>
#include <string_view>
#include <variant>
#include <chrono>
#include <thread>
#include <limits>
#include <jsoncpp/json/json.h>
